name: wcwidth() test
run-name: ${{ github.actor }} test of wcwidth() on various OSes
on: [push]
jobs:
  Test-wcwidth:
    runs-on: macos-latest
    steps:
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: List files
        run: |
          ls ${{ github.workspace }}
      - name: Compile
        run: |
          cc testwcw.c -o testwcw
      - name: Run
        run: |
          uname -a
          ./testwcw
          
          
